# Generated by Django 4.2.3 on 2023-07-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_rename_user_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
